### ISSUE TITLE
Attribute title is not correct in ReportPage

### ISSUE THREAD

**Issue by vhtien** [martiner/gooddata-java#364]
Use template: `/projectTemplates/GoodSalesDemo/2`

Create a report contains:
WHAT: `Amount`
HOW: `Sales Rep`

```java
final Metric amountMetric = getMdService().getObj(getProject(), Metric.class, title(METRIC_AMOUNT));
final Attribute saleRep = getMdService().getObj(getProject(), Attribute.class, title(SALES_REP));

ReportDefinition definition = GridReportDefinitionContent.create(SIMPLE_REPORT,
    singletonList(METRIC_GROUP),
    singletonList(new AttributeInGrid(saleRep.getDefaultDisplayForm())),
    singletonList(new MetricElement(amountMetric)));
definition = getMdService().createObj(getProject(), definition);
getMdService().createObj(getProject(), new Report(definition.getTitle(), definition));
```

Open that report in UI, the title of `Sales Rep` will be replaced by `Owner Name`, which is the title of default display form.

**Comment by jimirocks** [comment]
Well this is expected -  as described in javadoc of `new AttributeInGrid(DisplayForm)`:

> Creates new AttributeInGrid using given DisplayForm's uri and it's title as alias.

**Comment by vhtien** [comment]
Use `new AttributeInGrid(Attribute attr)` is the same. Is it expected as well?

**Comment by jimirocks** [comment]
Please read the javadoc and answer.

### Additional info:
Previously there was only possibility to create AttributeInGrid from URI, which resulted in alias set to empty String (this deprecated constructor is broken in 2.0.0-RC.1 but already fixed in 2.0.0-RC branch). My guess is that UI behaves the way, it replaces empty String with Attribute's title. 
The question is whether the `new AttributeInGrid(Attribute)` shouldn't use attribute's title rather than default display form - @martiner what do you think?.

**Comment by jimirocks** [comment]
@vhtien would you (as SDK user) expect that constructor taking `Attribute`, have alias set from Attribute's title? Is it more logical? 

Currently the alias is taken from defaultDisplayForm because the AttributeInGrid's uri must point to displayForm - so we took uri and alias from the same object.

**Comment by vhtien** [comment]
well, as SDK user, I need the SDK provide exactly what I've done in UI. And I believe that create a report with attribute have the alias set from that attribute.

**Comment by jimirocks** [comment]
Current way to behave as the UI (my guess): `new AttributeInGrid(attr.getDefaultDisplayForm().getUri(), "")` or better  `new AttributeInGrid(attr.getDefaultDisplayForm().getUri(), attr.getTitle())`.

More constructors, as well  as change of the `new AttributeInGrid(Attribute)` to use attribute's title will be in next RC version.
