### ISSUE TITLE
Register services as spring beans

### ISSUE THREAD

**Issue by jimirocks** [martiner/gooddata-java#376]
When instance of GoodData is created as a spring bean all service could be automaticaly registered as beans as well.

It should be implemented by noninvasive way (the plain old constructor should not trigger some spring magic)

**Comment by martiner** [comment]
We can annotate `getXyzService()` methods with `@Bean` annotation.

**Comment by jimirocks** [comment]
That was my first intention, but it would imply adding `spring-context` to dependencies...
